name: ui_payload
description: Semantic UI content representation. Separate text and severity from presentation for i18n-ready, framework-agnostic payloads.
version: 0.1.0
repository: https://github.com/CardosoShlomo/ui_payload

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0